server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: qrbtf
  static_configs:
  - targets:
      - localhost
    labels:
      job: qrbtf-api
      __path__: /var/log/qrbtf-api/*.log
  - targets:
      - localhost
    labels:
      job: qrbtf-bot
      __path__: /var/log/qrbtf-bot/*.log